### ISSUE TITLE
fix: race condition between SceneBoundariesDebugModeChecker and Material component prevents them to work properly

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#32] opened 2019-11-11 18:27 UTC
To test this, checkout the `-1.73 transparent planes` scene. You can observe it fails to set the texture correctly.

**Comment by BrianAmadori** [comment] 2020-08-20 15:28
Duplicate of https://github.com/decentraland/explorer/issues/848

**Closed as completed by BrianAmadori** 2020-08-20 15:28 UTC
Labels: bug, low priority
