### ISSUE TITLE
Avatar modifier areas only work if at ground level

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1670] opened 2020-11-19 21:50 UTC
This was reported by Corv from the community (Corv#5448)
It seems like Avatar Modifier Areas only work if they are at ground level

He says:

If you put something higher than position.y greater than 0 it wont work.

He has tried with 6.6.1 and still faces the problem.

**Comment by AjimenezDCL** [comment] 2021-01-13 09:27
https://user-images.githubusercontent.com/50231608/104432899-c6da2e00-5589-11eb-9faa-1889a63686ab.mp4

I cannot reproduce it. Going to close it! If the issue arises again let's try to get a repro scene.

**Closed as completed by AjimenezDCL** 2021-01-13 09:27 UTC
Labels: bug
