### ISSUE TITLE
[Severe] Materials not being loaded (race condition?)

### ISSUE THREAD

**Issue by eordano** [decentraland/explorer#713] opened 2020-03-07 06:17 UTC
Expected Behavior:
![image](https://user-images.githubusercontent.com/42750/76138008-fba05f00-6021-11ea-96ee-638938c83eaf.png)
What's happening:
First time I load the preview, the material is not loaded:
![image](https://user-images.githubusercontent.com/42750/76138011-0b1fa800-6022-11ea-8781-c0a03db67042.png)
After reloading the scene, it works.

This is likely to be causing a lot of weirdness in scenes.

Sample scene to repro:

```//Create entity and assign shape
const myEntity = new Entity()
myEntity.addComponent(new BoxShape())

//Create material and configure its fields
const myMaterial = new Material()
myMaterial.albedoColor = Color3.Blue()
myMaterial.metallic = 0.9
myMaterial.roughness = 1

//Assign the material to the entity
myEntity.addComponent(myMaterial)

// Create and add a `Transform` component to that entity
myEntity.addComponent(new Transform())

// Set the fields in the component
myEntity.getComponent(Transform).position.set(3, 1, 3)

// Add the entity to the engine
engine.addEntity(myEntity)
```

**Comment by BrianAmadori** [comment] 2020-03-09 13:54
Maybe its a dupe of #32

**Comment by pbosio** [comment] 2021-01-12 19:41
I just tested this code both in @latest and @next and it's working fine.
Can we assume this issue is already fixed?

**Closed as completed** 2021-01-18 20:00 UTC
Labels: bug, needs validation, SDK
