### ISSUE TITLE
Some of Aetheria's land doesn't show in maps, cannot use /goto.

### ISSUE THREAD

**Issue by cfravel** [decentraland/explorer#1624] opened 2020-11-15 00:10 UTC
About 2000 of Aetheria's 10,005 parcels had to be allocated east of x=150 and north of y=150. because the original map didn't accomodate all of Aetheria's contributions.

Decentraland thankfully partially fixed this before the land went to the DAO by adding the remaining parcels to the east of X=150 and north of y=150.

Some of our privately-allocated land is outside 150,150, and much of our community land is.
The support for these Aetherian parcels is not complete, though, and should be corrected asap because we have contributors ready to deploy to their allocated plots.

Here is what works and what doesn't:

--- GOOD / WORKS
- You can URL to such land.  This works, for example:  //https://play.decentraland.org/?position=151%2C151&realm=fenrir-amber
- We can assign operator wallets to valid parcels in Aetheria outside 150,150.  (or at least did as of 9/11/2020)
- The SDK can deploy to them if the operator has been set  (or at least did as of 9/11/2020).  You can see a default sdk scene that was deployed on 9/11/2020 to 151,151 for example.
- I think that the Builder shows your operator wallet parcels even if they are outside 150,150, and you can deploy with the Builder (This needs to be confirmed.)

--- What doesn't work:
- This does not, and should:  /goto 151,151
- dcl info 151,151 doesn't show information and it should
- dcl info 150,150 doesn't show Aetheria parcels beyond 150
- When you are in that region beyond 150,150, the "where you are" indicator in the minimap doesn't report that you are in Aetheria.
- The builder scene-deployment map shows land allocated to contributors that have LandUpdateOperator set parcels is outside, but it doesn't show as being inside the blue district.  See example in image attached below.
- https://land.decentraland.org/ doesn't show the district parcels that are in that outer zone.

---- Here is the documentation on the Aetheria district and how users find their way to their allocated plots:
https://docs.google.com/document/d/1FnN4mP8tuA5ol-wfPiFwHPzIIwEQ8tOOfewef4SkzHA/edit#heading=h.70r6ffbokzuv

---- Here is a map of the district as fully allocated to 10,005 parcels.
 https://aetheria.io/documents/225KB_Lite_Aetheria_Maps.xlsx

**Comment by cfravel** [comment] 2020-11-15 00:13
This image is from Builder deployment map, showing the parcels that have this user's wallet as Land UpdateOperator.  Among the parcels in this plot is 115,154.

![Builder_shows_115_154_to_operator_but_outside_district](https://user-images.githubusercontent.com/21015643/99159752-1c3ab180-26a5-11eb-8125-9059a3a1d8ef.png)

**Comment by nchamo** [comment] 2020-11-16 12:41
It seems that there are some cross-project issues handing Aetheria
cc @marcosnc, @nachomazzara, @menduz, @eordano

**Comment by cfravel** [comment] 2021-02-21 18:31
The Builder now cannot deploy to district land using either the estate UpdateManager or UpdateOperator wallets.  This is hindering district decoration.

**Comment by nachomazzara** [comment] 2021-02-22 13:13
@cazala can you take a look?

**Comment by cfravel** [comment] 2021-03-05 22:30
@marcosnc, @nachomazzara, @menduz, @eordano any progress?
I'm going to be soon expected to deploy a bunch of cyberpunk contest scenes to Aetheria, and would like to have the option of doing this with the Builder.

**Comment by eordano** [comment] 2021-03-06 01:32
This should be fixed by:

```
const ranges = [
    {
        x: { from: -150, to: 150 },
        y: { from: -150, to: 150 },
    },
    {
        x: { from: 62, to: 163 },
        y: { from: 151, to: 158 },
    },
    {
        x: { from: 151, to: 162 },
        y: { from: 144, to: 150 },
    },
    {
        x: { from: 151, to: 163 },
        y: { from: 59, to: 143 },
    }
]

function isValidCoordinate(target: { x: number, y: number }) {
  for (let range of ranges) {
    if (target.x >= range.from.x && target.x <= range.to.x &&
        target.y >= range.from.y && target.y <= range.to.y) {
      return true
    }
  }
  return false
}
```

**Comment by menduz** [comment] 2021-03-06 12:43
@marcosnc and @nachomazzara you have the monkey, it should be a quick patch

**Comment by marcosnc** [comment] 2021-03-06 13:02
The content server has no restriction on the parcel's coordinates as long as the deployer has permissions to deploy on it.
We have some minor changes needed in explorer but they don't affect the deployment.

**Comment by cazala** [comment] 2021-03-06 16:30
hey guys, the issue is with ‘react-tile-map’ (used by the Atlas) which takes maxX, maxY, minX, minY props, and doesn’t report onClick events outside of that area. I can’t just increase those props to include the coords outside of 150, cos clicking on empty parcels outside 150 could break some parts of the code. I haven’t been able to fix it yet because i’ve been focusing fully on shipping the matic bridge, but if this is a priority i ll have it fixed on Monday.

**Comment by cazala** [comment] 2021-03-08 16:15
Sorry my comment above was meant for https://github.com/decentraland/builder/issues/1263 I got the issues mixed up 😅

**Comment by cfravel** [comment] 2021-03-11 19:54
The main remaining problem in the Aetheria district is that you cannot go directly to its lands beyond 150.

You must go to a parcel within 150 and walk out.

This affects URL, /goto, Builder jump in, 

and presumably event Jump In and Explore and Play jump in.

**Comment by marcosnc** [comment] 2021-03-12 14:17
The /goto problem is addressed here: https://github.com/decentraland/explorer/pull/2198

**Closed as completed** 2021-03-12 14:17 UTC
Labels: bug, bug:critical, kernel

**Comment by cfravel** [comment] 2021-04-05 03:28
There are still several issues with url or goto in Aetheria >150,150
https://github.com/decentraland/explorer/issues/2260
