### ISSUE TITLE
Pausing video not working in older versions

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#1206] opened 2020-08-21 22:21 UTC
It seems that pausing a video worked well on version 6.4.8
But on versions 6.4.9 and 6.4.10, you can pause a video, but if you play again, it goes back to the start instead of playing from where it was paused. This behavior has changed in the las few releases.

In this scene you can see that.  If you use 6.4.8 pausing and playing again works fine
With latest, if you pause then playing again starts from the start

[https://app.zenhub.com/files/220994476/aec0e479-40b7-45c7-a29e-716725cd8d75/download](https://app.zenhub.com/files/220994476/aec0e479-40b7-45c7-a29e-716725cd8d75/download)

**Comment by AjimenezDCL** [comment] 2020-10-26 08:34
~I cannot reproduce it using test scenes. Could we get some validation or close it?~

Nevermind, just reproduced it.

**Comment by AjimenezDCL** [comment] 2020-10-26 16:50
Yeah this is super weird. In Unity + local build using a test scene this works perfectly but in preview mode the bug is presented (maybe the renderer used by the CLI is outdated?). 

After Halloween is over we will come back to this with a real deployed scene and check what's happening.

**Closed as completed** 2021-01-19 15:15 UTC
Labels: bug, needs validation, mid priority
