### ISSUE TITLE
Rendering of some scenes stutters strangely

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#677] opened 2020-03-03 15:46 UTC
This scene renders with a strange stutter when you walk up to it
https://play.decentraland.org/?position=-16%2C-5

It seems to render well if you load into it directly
But if you walk up to it from far away, like from 0,0  you will see this strange effect, where it seems that it attempts to render it and fails many times. It eventually does succeed after what look like many failed attempts

This also happens in the las vegas casinos
Serinity casino.  -55,143
Chateau Satoshi's -75,73

**Comment by BrianAmadori** [comment] 2020-04-20 14:16
Dupe of #785

**Closed as completed by BrianAmadori** 2020-04-20 14:16 UTC
