### ISSUE TITLE
Ensure the map is always centered when it's opened

### ISSUE THREAD

**Issue by marcosnc** [decentraland/explorer#1006] opened 2020-06-05 14:56 UTC
When the map is opened it must be centered in the user's position.

**Comment by BrianAmadori** [comment] 2020-08-20 15:40
This is not a bug, is a feature request. Just removed the label to reflect that.

**Comment by AjimenezDCL** [comment] 2020-10-26 12:47
This is already implemented, you can actually see it working in production atm.

I'm closing this

**Closed as completed by AjimenezDCL** 2020-10-26 12:47 UTC
Labels: good first issue
